apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: new_project
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoidGFsYXNodGVzdHMiLCJwYXNzd29yZCI6ImdocF96aFUzYjBJVzRiUVhEdmZHSkxER2pDazNQYTZicVczUG51TTkiLCJhdXRoIjoiQkFTRTY0KHVzZXJuYW1lOnBhc3N3b3JkKSJ9fX0=
