apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: new_project
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAidGFsYXNodGVzdHMiLAogICAgICAicGFzc3dvcmQiOiAiZ2hwX3dON0FxaVhwSWh1WWRLQ2w0N3lXbHpsd0lRTVZaSzJBalFqSSIsCiAgICAgICJhdXRoIjogImRHRnNZWE5vT21kb2NGOTNUamRCY1dsWWNFbG9kVmxrUzBOc05EZDVWMng2YkhkSlVVMVdXa3N5UVdwUmFraz0iCiAgICB9CiAgfQp9Cg==
